#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["Application/Book.API/Book.API.csproj", "Application/Book.API/"]
COPY ["Domain/Bookstore.Domain/Bookstore.Domain.csproj", "Domain/Bookstore.Domain/"]
COPY ["Infrastructure/Book.Infrastructure/Book.Infrastructure.csproj", "Infrastructure/Book.Infrastructure/"]
COPY ["Shared/Bookstore.Api.Enum/Bookstore.Api.Enum.csproj", "Shared/Bookstore.Api.Enum/"]
RUN dotnet restore "Application/Book.API/Book.API.csproj"
COPY . .
WORKDIR "/src/Application/Book.API"
RUN dotnet build "Book.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Book.API.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENV ASPNETCORE_URLS=http://+:8080
ENTRYPOINT ["dotnet", "Book.API.dll"]