#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["Application/Basket.API/Basket.API.csproj", "Application/Basket.API/"]
COPY ["Domain/Bookstore.Domain/Bookstore.Domain.csproj", "Domain/Bookstore.Domain/"]
COPY ["Infrastructure/Basket.Infrastructure/Basket.Infrastructure.csproj", "Infrastructure/Basket.Infrastructure/"]
COPY ["Shared/Bookstore.Api.Enum/Bookstore.Api.Enum.csproj", "Shared/Bookstore.Api.Enum/"]
COPY ["Shared/Bookstore.Api.Helper/Bookstore.Api.Helper.csproj", "Shared/Bookstore.Api.Helper/"]
RUN dotnet restore "Application/Basket.API/Basket.API.csproj"
COPY . .
WORKDIR "/src/Application/Basket.API"
RUN dotnet build "Basket.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Basket.API.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENV ASPNETCORE_URLS=http://+:8081
ENTRYPOINT ["dotnet", "Basket.API.dll"]